name: package_ekyc
description: "A new Flutter plugin project."
version: 0.0.1
# homepage:
environment:
  sdk: ">=3.4.0 <4.0.0"
  # flutter: '>=3.3.0'

# dependency_overrides:
#   dio: ^5.4.2+1
#   intl: 0.18.0
#   flutter_nfc_kit: 3.6.0

dependencies:
  # flutter_nfc_kit: 3.6.0
  chewie: 1.10.0
  another_flushbar: ^1.12.30
  app_settings: 5.1.1
  asn1lib: ^1.5.3
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  camera: 0.10.6
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  dmrtd:
    git:
      url: https://github.com/HVLoc/dmrtd
      ref: master
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_pdfview: ^1.2.7
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.5
  get: ^4.6.6
  google_fonts: 6.1.0
  google_mlkit_face_detection: ^0.12.0
  hive: ^2.2.3
  image: ^4.1.3
  image_picker: ^1.0.5
  just_audio: ^0.9.38
  loading_overlay_pro: ^2.1.1
  local_auth: ^2.2.0
  logger: ^2.2.0
  mobile_scanner: 5.2.3
  nfc_manager: ^3.4.0
  package_info_plus: ^8.2.1
  percent_indicator: ^4.2.3
  permission_handler: 11.3.1
  plugin_platform_interface: ^2.0.2
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  url_launcher: ^6.2.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: vn.lochv.package_ekyc
        pluginClass: PackageEkycPlugin
      ios:
        pluginClass: PackageEkycPlugin
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by SoftDreams Developer
    # **************************************************************************

    - assets/jpg/
    - assets/locales/
    - assets/png/
    - assets/svg/

  # assets end
